### ISSUE TITLE
Plan Workflow and design software architecture

### ISSUE THREAD

**Issue by MerMer12345** [JoatXI/recipe-app#2]
Make and write down a plan that documents the general software architecture, technologies used, pipeline and workflow of the Project.

Discuss GitHub usage and rules 

Document each members role and responsibilities.

**Comment by JoatXI** [comment]
Following the Figma template provided by @MerMer12345 I have created a new branch for the implementation of our application API. Bear in mind that this will serve as a temporary server because from out last Teams Meeting @MerMer12345 agreed to create the database using MongoDB.

So for the temporary API I'm creating I am using an sqlite3 database both for storing the various recipes and also for storing the session variables that will handle the user registration and login.

GITHUB RULES:
Rule 1:  DO NOT PUSH TO THE MASTER BRANCH!!

I want to mention that for every feature that an individual is responsible for implementing remember to create a different branch for it, as we will only merge it to the master branch after everyone has reviewed the implemented feature. DO NOT PUSH TO THE MASTER BRANCH!!

Finally, if anyone does not have understanding of how to use GitHub branches or any other technology please do not hesitate mention this to the group as we need to work together to complete this project successfully.

SIDE NOTE: I am currently having a little trouble with my school email and currently do not have access to Teams so on Tuesday 22nd of October we can discuss how to go about our future meetings if necessary.
